### ISSUE TITLE
Neovim support

### ISSUE THREAD

**Issue by kdheepak** [axelf4/vim-strip-trailing-whitespace#1]
This is the error I'm getting when I try to install it right now in neovim. 
```
Error detected while processing /Users/USER/.local/share/nvim/plugged/vim-strip-trailing-whitespace/plugin/strip_trailing_whitespace.vim:
line    2:
E492: Not an editor command: scriptversion 4
Error detected while processing function <SNR>96_OnBufEnter:
line    4:
E117: Unknown function: listener_add
Press ENTER or type command to continue
```

I'm assuming this is a neovim / vim difference? Are you planning to support neovim? 

Thanks for making this plugin!

**Comment by axelf4** [comment]
Neovim is something I want to support, but it's not my highest priority.

The incompatibility stems from Vim and Neovim having different API:s for listening to buffer changes. The corresponding Neovim API seems to be `nvim_buf_attach`. `scriptversion 4` is nonobligatory and not an issue.

First step would be to get CI to run tests on Neovim too while allowing failures.

**Comment by kdheepak** [comment]
Awesome! Thanks!
